export const skills = [
  { skill: 'HTML', value: 90 },
  { skill: 'CSS', value: 80 },
  { skill: 'JavaScript', value: 90 },
  { skill: 'React', value: 90 },
  { skill: 'Node', value: 60 },
]

export const projects = [
  {
    image: 'markus-spiske-qjnAnF0jIGk-unsplash.jpg',
    name: 'Best of 90s',
    description: 'Augmented reality gallery.',
    stack: 'Typescript, Three.js, JSARToolkit',
    repo: 'https://github.com/MaxBrokhman/best-of-90s',
  },
  {
    image: 'nerds.png',
    name: 'Nerds',
    description: 'Web studio site.',
    stack: 'HTML, CSS, JavaScript',
    repo: 'https://github.com/MaxBrokhman/nerds',
  },
  {
    image: 'calc.png',
    name: 'Terms of stay calculator',
    description: 'For foreign citizens in Russia.',
    stack: 'HTML, CSS, JavaScript',
    repo: 'https://github.com/MaxBrokhman/terms-of-stay-calculator.io',
  },
  {
    image: 'swdb.png',
    name: 'Star Wars Database',
    description: 'Database of Star Wars universe.',
    stack: 'React, Bootstrap',
    repo: 'https://github.com/MaxBrokhman/sw-db',
  },
  {
    image: 'dev.png',
    name: 'Devconnector',
    description: 'Social network for developers.',
    stack: 'React, Redux, Node, Express, Github API',
    repo: 'https://github.com/MaxBrokhman/devconnector',
  },
  {
    image: 'florian-olivo-4hbJ-eymZ1o-unsplash.jpg',
    name: 'Task Manager API',
    description: 'REST API server for task manager application.',
    stack: 'Node, Express, MongoDB, Mongoose. Jest and supertest for testing',
    repo: 'https://github.com/MaxBrokhman/task-manager-server',
  },
  {
    image: 'guess.png',
    name: 'Guess melody',
    description: 'SPA game.',
    stack: 'React, Typescript, Jest, Enzyme',
    repo: 'https://github.com/MaxBrokhman/guess-melody',
  },
  {
    image: 'chat.png',
    name: 'Chat',
    description: 'Online SSR chat.',
    stack: 'Node, Express, Socket IO',
    repo: 'https://github.com/MaxBrokhman/chat-app',
  },
  {
    image: 'six.png',
    name: 'Six Cities',
    description: 'Booking SPA.',
    stack: 'React, Typescript, Jest, Enzyme',
    repo: 'https://github.com/MaxBrokhman/six-cities',
  },
  {
    image: 'lh.png',
    name: 'Learn Hebrew',
    description: 'Very simple, but effective app to remember hebrew words.',
    stack: 'React, Typescript, lodash',
    repo: 'https://github.com/MaxBrokhman/learn-hebrew',
  },
]
